version: "3"
services:

    poll:
        build: ./poll
        restart: always
        links:
          - redis
          - db
        depends_on:
          - redis
        ports:
          - "5000:80"
        networks:
          - poll-tier
        environment:
          - 0.0.0.0

    redis:
        image: redis:buster
        restart: always
        expose:
          - "6379"
        ports:
          - "6379:6379"
        networks:
          - poll-tier
          - back-tier

    worker:
        build: ./worker
        restart: always
        links:
          - redis:redis
          - db:db
        depends_on:
          - db
          - redis
          - result
        networks:
          - back-tier
        environment:
          - 0.0.0.0

    result:
        build: ./result
        restart: always
        depends_on:
          - db
        ports:
          - "5001:80"
        networks:
          - result-tier
        environment:
          - 0.0.0.0

    db:
        image: postgres
        restart: always
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        volumes:
          - "./schema.sql:/docker-entrypoint-initdb.d/init.sql"
          - db-data:/var/lib/postgresql/data
        networks:
          - result-tier
          - back-tier

networks:
    poll-tier:
    result-tier:
    back-tier:

volumes:
    db-data: