##
## EPITECH PROJECT , 2019
## MAKEFILE DAY12
## File description :
##

SRC = cat.c \
	my_putchar.c \
	my_putstr.c

OBJ = $(SRC:.c=.o)

NAME = cat

all:	$(NAME)

$(NAME):		$(OBJ)
		

clean:
		rm -f $(OBJ)

fclean:		clean
		rm -f $(NAME)

re:		fclean all